### ISSUE TITLE
Confirm Search Functionality

### ISSUE THREAD

**Issue by jamstooks** [AASHE/django-aashestrap#2]
Hey Scott,

Could you confirm that the search functionality is the same as on the primary site? It's just a google custom search engine box, that should be really easy to duplicate...

Thanks!
-Ben

**Comment by baronvonvaderham** [comment]
Commit f355a8749577c408076d2321d783f7c4d36a5f42 addresses this.

The search bar on aashe.org did contain an additional drop-down selector, but it didn't fit, nor was it being used in the first place, so I just excluded that bit.
